---
# handlers file for ansible-zeek

- name: deploy zeek
  shell:
    chdir: /opt/zeek/bin
    cmd: ./zeekctl deploy
  async: 120 # set max run-time to 2 min
  poll: 5 # check every 5 sec for complete