---
# handlers file for ansible-zeek

- name: zeek | deploy
  become: yes
  environment:
    PATH: '/opt/zeek/bin:{{ ansible_env.PATH }}'
  shell:
    cmd: zeekctl deploy
  async: 120 # set max run-time to 2 min
  poll: 5 # check every 5 sec for complete