---
# handlers file for ansible-zeek

- name: deploy zeek
  environment:
    PATH: '/opt/zeek/bin:{{ ansible_env.PATH }}'
  shell:
    cmd: zeekctl deploy
  async: 120 # set max run-time to 2 min
  poll: 5 # check every 5 sec for complete

- name: install zkg packages
  environment:
    PATH: '/opt/zeek/bin:{{ ansible_env.PATH }}'
  shell:
    cmd: zkg autoconfig && zkg install zeek-community-id ja3 hassh
  async: 120
  poll: 5